site_name: Andy's Technical Scratchpad
site_url: https://knappek.github.io
copyright: >
  Copyright &copy; 2024 Andreas Knapp –
  <a href="#__consent">Change cookie settings</a>
repo_name: 'Knappek/Knappek.github.io'
repo_url: 'https://github.com/Knappek/Knappek.github.io'

docs_dir: 'docs'

nav:
- Home: index.md
- Kubernetes:
  - Kubernetes Architecture Concepts: kubernetes/architecture-concepts.md
- Tanzu:
  # - Tanzu Platform:
  #   - Tanzu Platform Technical Details: tanzu/tanzu-platform/tanzu-platform-technical-details.md
  - TKGS:
    - Integration with NSX-T: tanzu/tkgs/tkgs-nsxt-integration.md
    - Failed Supervisor Cluster upgrade: tanzu/tkgs/supervisor-cluster-upgrade-failed-in-vsphere-8.md
    - Airgapped TKGS homelab environment: tanzu/tkgs/tkgs-airgapped.md
    - Disaster Scenarios: tanzu/tkgs/disaster-scenarios.md
  - Tanzu Packages:
    - Intro: tanzu/tanzu-packages/index.md
    - Airgapped Installation: tanzu/tanzu-packages/deploy-packages-airgapped.md
  - Platform Automation Toolkit:
    - tanzu/platform-automation-toolkit/index.md
    - Install Concourse for Platform Automation: tanzu/platform-automation-toolkit/install-concourse-for-platform-automation.md
    - Deploy vSphere + NSX-T to be used for TAS and TKGI: tanzu/platform-automation-toolkit/deploy-vsphere-with-nsxt-for-tas-tkgi.md
    - Deploy TAS and TKGI with Concourse: tanzu/platform-automation-toolkit/deploy-tas-tkgi-with-concourse.md
- Homelab:
  - Setup: homelab/index.md
  - Airgapped TKGS homelab environment: homelab/airgapped-tkgs.md
- Misc:
  - Deploy Ubuntu VM on vCenter: misc/deploy-ubuntu-on-vcenter.md
  - NSX REST API: misc/nsx-rest-api.md
 

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - toc.follow
  language: 'en'

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  analytics:
    provider: google
    property: G-0VCFRTY9ME
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Knappek
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/andy-knapp-6a72b6108

plugins: 
  - glightbox # makes images clickable: https://github.com/blueswen/mkdocs-glightbox
  - search # searchbar
  - git-revision-date-localized: # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      locale: en
      exclude:
        - index.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # info blocks starting with !!!, e.g. !!! warning
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
