site_name: Andy's Technical Scratchpad
site_url: https://knappek.github.io
copyright: 'Copyright &copy; 2024 Andreas Knapp'
repo_name: 'Knappek/Knappek.github.io'
repo_url: 'https://github.com/Knappek/Knappek.github.io'

docs_dir: 'docs'

nav:
- Home: index.md
- Kubernetes:
  - Kubernetes Architecture Concepts: kubernetes/architecture-concepts.md
- Tanzu:
  - Tanzu Platform:
    - Tanzu Platform Technical Details: tanzu/tanzu-platform/tanzu-platform-technical-details.md
  - TKGS:
    - Supervisor Cluster upgrade failed in vSphere 8u2b: tanzu/tkgs/supervisor-cluster-upgrade-failed-in-vsphere-8.md
    - Set up an airgapped TKGS homelab environment: tanzu/tkgs/tkgs-airgapped.md
    - vSphere with Tanzu integration with NSX-T: tanzu/tkgs/tkgs-nsxt-integration.md
    - Set up an airgapped TKGS homelab environment: tanzu/tkgs/tkgs-airgapped.md
  - Tanzu Packages:
    - Intro: tanzu/tanzu-packages/index.md
    - Airgapped Installation: tanzu/tanzu-packages/deploy-packages-airgapped.md
- Homelab:
  - Setup: homelab/index.md
  - Set up an airgapped TKGS homelab environment: homelab/airgapped-tkgs.md
 

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy
    - toc.follow
    - search.suggest
  language: 'en'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Knappek
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/andy-knapp-6a72b6108

plugins: 
  - glightbox # makes images clickable: https://github.com/blueswen/mkdocs-glightbox
  - search # searchbar
  - git-revision-date-localized: # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      locale: en
      exclude:
        - index.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # info blocks starting with !!!, e.g. !!! warning
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
