site_name: Andy's Technical Scratchpad
site_url: https://knappek.github.io
copyright: 'Copyright &copy; 2024 Andreas Knapp'
repo_name: 'Knappek/Knappek.github.io'
repo_url: 'https://github.com/Knappek/Knappek.github.io'

docs_dir: 'docs'

nav:
- Home: 
  - Welcome: index.md
- vSphere with Tanzu:
  - Upgrade TKGS: vsphere-with-tanzu/update-tkgs-from-vsphere7-to-vsphere8.md
  - Tanzu Packages:
    - Intro: vsphere-with-tanzu/tanzu-packages/index.md
    - Airgapped Installation: vsphere-with-tanzu/tanzu-packages/deploy-packages-airgapped.md
- Homelab:
  - Setup: homelab/index.md
  - Set up an airgapped TKGS homelab environment: homelab/airgapped-tkgs.md
 

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy
    - toc.follow
  language: 'en'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Knappek
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/andy-knapp-6a72b6108

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # info blocks starting with !!!, e.g. !!! warning
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


